# Generated by Django 5.0.3 on 2024-04-05 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("EducaPlus", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("nivel", models.CharField(max_length=255)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=6)),
                ("categoria", models.CharField(max_length=255)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EducaPlus.instructor",
                    ),
                ),
            ],
        ),
    ]
