# Generated by Django 5.0.3 on 2024-04-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("EducaPlus", "0002_curso"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="descripcion",
            field=models.TextField(default="Sin descripción"),
        ),
    ]
