# Generated by Django 5.0.3 on 2024-04-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("EducaPlus", "0003_curso_descripcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="duracion",
            field=models.IntegerField(default=0),
        ),
    ]
